export const data_HTTT = [
    {
        masv: '3119560010',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Kỹ thuật phần mềm',
        trangthai: 1,
    },
    {
        masv: '3119560011',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Kỹ thuật phần mềm',
        trangthai: 1,
    },
    {
        masv: '3119560012',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Kỹ thuật phần mềm',
        trangthai: 1,
    },
    {
        masv: '3119560013',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Kỹ thuật phần mềm',
        trangthai: 1,
    },
    {
        masv: '3119560014',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Kỹ thuật phần mềm',
        trangthai: 1,
    },
    {
        masv: '3119560015',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Kỹ thuật phần mềm',
        trangthai: 1,
    },
    {
        masv: '3119560016',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Kỹ thuật phần mềm',
        trangthai: 1,
    },
    {
        masv: '3119560017',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Kỹ thuật phần mềm',
        trangthai: 1,
    },
    {
        masv: '3119560018',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Kỹ thuật phần mềm',
        trangthai: 1,
    },
    {
        masv: '3119560019',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Kỹ thuật phần mềm',
        trangthai: 1,
    },
    {
        masv: '3119560020',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Kỹ thuật phần mềm',
        trangthai: 1,
    },
    {
        masv: '3119560021',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Kỹ thuật phần mềm',
        trangthai: 1,
    },
]

const data_KHMT = [
    {
        masv: '3119560010',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Kỹ thuật phần mềm',
        trangthai: 1,
    },
    {
        masv: '3119560011',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Kỹ thuật phần mềm',
        trangthai: 1,
    },
    {
        masv: '3119560012',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Kỹ thuật phần mềm',
        trangthai: 1,
    },
    {
        masv: '3119560013',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Kỹ thuật phần mềm',
        trangthai: 1,
    },
    {
        masv: '3119560014',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Kỹ thuật phần mềm',
        trangthai: 1,
    },
    {
        masv: '3119560015',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Kỹ thuật phần mềm',
        trangthai: 1,
    },
    {
        masv: '3119560016',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Kỹ thuật phần mềm',
        trangthai: 1,
    },
    {
        masv: '3119560017',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Kỹ thuật phần mềm',
        trangthai: 1,
    },
    {
        masv: '3119560018',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Kỹ thuật phần mềm',
        trangthai: 1,
    },
    {
        masv: '3119560019',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Kỹ thuật phần mềm',
        trangthai: 1,
    },
    {
        masv: '3119560020',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Kỹ thuật phần mềm',
        trangthai: 1,
    },
    {
        masv: '3119560021',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Kỹ thuật phần mềm',
        trangthai: 1,
    },
]


const data_KTPM = [
    {
        masv: '3119560010',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Kỹ thuật phần mềm',
        trangthai: 1,
    },
    {
        masv: '3119560011',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Kỹ thuật phần mềm',
        trangthai: 1,
    },
    {
        masv: '3119560012',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Kỹ thuật phần mềm',
        trangthai: 1,
    },
    {
        masv: '3119560013',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Kỹ thuật phần mềm',
        trangthai: 1,
    },
    {
        masv: '3119560014',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Kỹ thuật phần mềm',
        trangthai: 1,
    },
    {
        masv: '3119560015',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Kỹ thuật phần mềm',
        trangthai: 1,
    },
    {
        masv: '3119560016',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Kỹ thuật phần mềm',
        trangthai: 1,
    },
    {
        masv: '3119560017',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Kỹ thuật phần mềm',
        trangthai: 1,
    },
    {
        masv: '3119560018',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Kỹ thuật phần mềm',
        trangthai: 1,
    },
    {
        masv: '3119560019',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Kỹ thuật phần mềm',
        trangthai: 1,
    },
    {
        masv: '3119560020',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Kỹ thuật phần mềm',
        trangthai: 1,
    },
    {
        masv: '3119560021',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Kỹ thuật phần mềm',
        trangthai: 1,
    },
]

const data_MMT = [
    {
        masv: '3119560010',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Kỹ thuật phần mềm',
        trangthai: 1,
    },
    {
        masv: '3119560011',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Kỹ thuật phần mềm',
        trangthai: 1,
    },
    {
        masv: '3119560012',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Kỹ thuật phần mềm',
        trangthai: 1,
    },
    {
        masv: '3119560013',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Kỹ thuật phần mềm',
        trangthai: 1,
    },
    {
        masv: '3119560014',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Kỹ thuật phần mềm',
        trangthai: 1,
    },
    {
        masv: '3119560015',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Kỹ thuật phần mềm',
        trangthai: 1,
    },
    {
        masv: '3119560016',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Kỹ thuật phần mềm',
        trangthai: 1,
    },
    {
        masv: '3119560017',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Kỹ thuật phần mềm',
        trangthai: 1,
    },
    {
        masv: '3119560018',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Kỹ thuật phần mềm',
        trangthai: 1,
    },
    {
        masv: '3119560019',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Kỹ thuật phần mềm',
        trangthai: 1,
    },
    {
        masv: '3119560020',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Kỹ thuật phần mềm',
        trangthai: 1,
    },
    {
        masv: '3119560021',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Kỹ thuật phần mềm',
        trangthai: 1,
    },
]